name: Deploy to WordPress.org

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: WordPress.org plugin directory
      url: https://wordpress.org/plugins/pronamic-pay-with-rabo-smart-pay-for-woocommerce/

    steps:
      - name: Release
        uses: pronamic/action-wordpress-plugin-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          svn-username: pronamic
          svn-password: ${{ secrets.SVN_PASSWORD }}
          tag: ${{ github.ref_name }}
          wp-slug: pronamic-pay-with-rabo-smart-pay-for-woocommerce
